# Generated by Django 4.0.3 on 2022-03-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_commentcrm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentcrm',
            name='comment_text',
            field=models.TextField(max_length=200, verbose_name='Текст комментария'),
        ),
    ]
